name: MinelesLibrary
version: '${version}'
authors: ['HeyMrau', 'KafeinDev']
main: net.mineles.library.loader.MinelesLibraryBukkitLoader
api-version: '1.13'
softdepend:  [ProtocolLib, Vault, PlaceholderAPI, ItemsAdder, ModelEngine]