name: MinelesLibrary
version: '${version}'
author: Mineles
main: net.mineles.library.loader.MinelesLibraryBukkitLoader
api-version: '1.13'
depend: [MinelesLibraryExternal]
softdepend:  [ProtocolLib, Vault, PlaceholderAPI, ItemsAdder, ModelEngine]